develop: rebuild project

diff --git a/docker/phpfpm/Dockerfile b/docker/phpfpm/Dockerfile
--- a/docker/phpfpm/Dockerfile
+++ b/docker/phpfpm/Dockerfile
@@ -1,7 +1,5 @@
 FROM php:7.2-fpm
 
-WORKDIR /var/www/html
-
 RUN apt-get update && apt-get install -y \
         libfreetype6-dev \
         libjpeg62-turbo-dev \
@@ -13,15 +11,33 @@ RUN apt-get update && apt-get install -y \
     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
     && docker-php-ext-install -j$(nproc) gd \
     && pecl install xdebug \
-    && docker-php-ext-enable xdebug \
- && curl -sS https://getcomposer.org/installer \
-  | php -- --install-dir=/usr/local/bin --filename=composer
+    && docker-php-ext-enable xdebug
 
-COPY xdebug.ini /usr/local/etc/php/conf.d/
-# Entrypoint script
-#COPY entrypoint.sh /var/
-#RUN chmod 777 /var/entrypoint.sh
-#ENTRYPOINT ["/var/entrypoint.sh"]
-#CMD ["docker-php-entrypoint", "php-fpm"]
+COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
 
-RUN usermod -u 1000 www-data
+# Cleanup dev dependencies
+#RUN apk del -f .build-deps
+
+ENV COMPOSER_ALLOW_SUPERUSER=1
+
+WORKDIR /var/www/html
+
+# prevent the reinstallation of vendors at every changes in the source code
+COPY composer.* ./
+
+RUN set -eux; \
+	composer install --prefer-dist --no-dev --no-autoloader --no-scripts --no-progress --no-suggest; \
+	composer clear-cache
+
+COPY . .
+RUN composer dump-autoload --classmap-authoritative; \
+	composer run-script --no-dev post-install-cmd; sync
+
+COPY docker/phpfpm/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
+RUN chmod +x /usr/local/bin/docker-entrypoint
+
+COPY docker/phpfpm/xdebug.ini /usr/local/etc/php/conf.d/
+
+ENTRYPOINT ["docker-entrypoint"]
+
+CMD ["php-fpm"]
